apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx2
spec:
  selector:
    matchLabels:
      run: my-nginx2
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx2
    spec:
      containers:
      - name: my-nginx2
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx2
  labels:
    run: my-nginx2
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: my-nginx2